### ISSUE TITLE
Material Theme: Chip

### ISSUE THREAD

**Issue by maier49** [dojo/themes#92]
**Enhancement**

Add a material theme for the new chip widget

**Comment by maier49** [comment]
So I've opened #98 , but I'm a little unclear on how to move forward with that. We went with renderer properties for the icons, but the material chip applies additional classes to the icon elements. Would we just assume that the provided icons will have the appropriate styles?

Should I add a wrapper to the leading icon and apply what I can there to match the material design?

**Comment by tomdye** [comment]
Can you not pass the appropriate classes in the icon renderer?
